server:
  port: 8080
  context-path: /api/v1

# mysql 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xdbin?characterEncoding=utf8&useSSL=true
    username: xdbin_db
    password: xdbin_db%rw
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # hibernate 是否修改表结构
    hibernate:
      ddl-auto: none
    # 是否显示 sql
    show-sql: true

path:
  blog: /Users/baoxuebin/Desktop/data/